# Ejercicio 9 

Toma $n$ como tu número publicado para el ejercicio 2. Escribe $n$ en base 2, y usa esas cifras para definir un polinomio, $f(x)$, donde tu bit más significativo defina el grado del polinomio $n$, el siguiente bit va multiplicado por $x^{n-1}$ y así sucesivamente hasta que el bit menos significativo sea el término independiente. El polinomio que obtienes es universal en el sentido de que tiene coeficientes en cualquier anillo.

Sea $f(x)$ el polinomio que obtienes con coeficientes en $\mathbb{Z}$.

1. Toma $g(x) \equiv f(x) \pmod{2}$ y halla el menor cuerpo de característica 2 que contenga a todas las raíces de g. ¿Qué deduces sobre la irreducibilidad de $g(x)$ en $\mathbb{Z}_2[x]$?
2. Extrae la parte libre de cuadrados de $g(x)$ y calcúlale la matriz de Berlekamp por columnas. Resuelve el sistema lineal $(B - Id)X = 0$.
3. Aplica el algoritmo de Berlekamp recursivamente si es necesario para hallar la descomposición en irreducibles de $g(x)$ en $\mathbb{Z}_2[x]$.
4. Haz lo mismo para hallar la descomposición en irreducibles de $f(x) \pmod{3}$.
5. ¿Qué deduces sobre la reducibilidad de $f(x)$ en $\mathbb{Z}[x]$?

In [143]:
import numpy as np

In [144]:
n = 77432081

In [145]:
format(n, 'b')

'100100111011000010100010001'

In [146]:
Z2 = PolynomialRing(GF(2), 'x')
x = Z2.gen()
g = 1 + x^4 + x^8 + x^10 + x^15 + x^16 + x^18 + x^19 + x^20 + x^23 + x^26

## Apartado 1

In [147]:
def menor_indice_cuerpo(f, p, x):
    g = x^p 
    g1 = (g - x).mod(f)
    k = 1
    
    while g1 > 0:
        g  = (g^p).mod(f)
        g1 = (g - x).mod(f)
        k = k + 1
        
    return k

In [148]:
menor_indice_cuerpo(g, 2, x)

616

El menor cuerpo de característica $2$ que contiene a todas las raíces de $g$ es $$F_{2^{2^3 * 7 * 11}} = F_{2^{8 * 7 * 11}}$$

In [149]:
factor(616)

2^3 * 7 * 11

Como $616 > \text{grado}(g) = 26$, entonces $g(x)$ es reducible en $\mathbb{Z}_2[x]$. (Esto no sale esto exactamente. Se rompe de otra manera. Mira el apartado 3) Por ello, $g(x)$ puede romperse en tres polinomios de grados $8, 7$ y $11$, ya que $8 + 7 + 11 = 26$

## Apartado 2

$g(x)$ es libre de cuadrados, así que no será necesario extraer nada. 

In [150]:
def extraer_B(g, p, field):
    # Asegúrate de que `g` está en el mismo cuerpo que `field`
    x = field.gen()
    B = np.zeros([g.degree(), g.degree()], dtype = int)

    for i in range(0, g.degree()):
        coeficientes = [0] * g.degree()

        pol = x^(p*i)
        pol = pol.mod(g)
        #print("[" + str(i) + "] x^2i mod f = " + str(pol))

        for j, coef in enumerate(pol.coefficients(sparse = False)):
            coeficientes[j] = coef

        B[i, :] = coeficientes
    return Matrix(field, B.tolist())

B = extraer_B(g, 2, Z2)

Nuestra matriz $B$ es 

In [151]:
B

26 x 26 dense matrix over Univariate Polynomial Ring in x over Finite Field of size 2 (using GF2X) (use the '.str()' method to see the entries)

In [152]:
print(B)

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 0 1 1 1 0 0 1 0 0]
[0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 0 1 1 1 0 0 1]
[0 1 0 0 1 1 0 0 1 1 0 1 1 0 1 0 1 1 0 0 0 1 1 1 0 0]
[0 0 0 1 0 0 1 1 0 0 1 1 0 1 1 0 1 0 1 1 0 0 0 1 1 1]
[1 1 0 0 1 0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 1 0 0 1 1 1]
[1 1 1 1 1 1 1 0 1 1 1 1 1 1

El rango de $B - I_d$ es $23$, así que habrá una única solución

In [153]:
(B - Matrix.identity(g.degree())).rank()

23

In [154]:
soluciones = (B - Matrix.identity(g.degree())).left_kernel()  # left o right?
soluciones

Free module of degree 26 and rank 3 over Univariate Polynomial Ring in x over Finite Field of size 2 (using GF2X)
Echelon basis matrix:
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 1 0 0 1 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1]
[0 0 0 1 1 1 1 1 0 0 0 1 0 1 0 0 0 1 0 0 1 0 1 0 0 0]

## Apartado 3

In [155]:
def sacar_soluciones(B, g, field):
    
    polinomios_soluciones = []
    soluciones = (B - Matrix.identity(g.degree())).left_kernel()

    for sol in list(soluciones.gens()):
        polinomios_soluciones.append(field(list(sol)))

    return polinomios_soluciones

polinomios_soluciones = sacar_soluciones(B, g, Z2)
polinomios_soluciones

[1,
 x^25 + x^23 + x^17 + x^16 + x^10 + x^9 + x^6 + x^3 + x^2,
 x^22 + x^20 + x^17 + x^13 + x^11 + x^7 + x^6 + x^5 + x^4 + x^3]

Como $\text{grado}(g) - \text{rango}(B - I_d) = 3$, vamos a necesitar tres polinomios para romper $g$. Esto nos lo decía también el primer apartado

In [156]:
g.degree() - (B - Matrix.identity(g.degree())).rank()

3

Vamos a aplicar calcular el $\text{mcd}(g, polinomio - c)$, con $c \in \mathbb{Z}_2$

In [157]:
for pol in polinomios_soluciones:
    if pol != 1:
        print("gcds de " + str(pol) + ": ")
        for c in range(0, Z2.modulus()):
            print("\t-> " + str(gcd(pol - c , g)))

gcds de x^25 + x^23 + x^17 + x^16 + x^10 + x^9 + x^6 + x^3 + x^2: 
	-> x^18 + x^17 + x^13 + x^10 + x^8 + x^7 + x^6 + x + 1
	-> x^8 + x^7 + x^6 + x^3 + x^2 + x + 1
gcds de x^22 + x^20 + x^17 + x^13 + x^11 + x^7 + x^6 + x^5 + x^4 + x^3: 
	-> x^11 + x^10 + x^7 + x^4 + x^3 + x + 1
	-> x^15 + x^14 + x^13 + x^11 + x^5 + x^4 + x^2 + x + 1


In [158]:
g2 =  x^25 + x^23 + x^17 + x^16 + x^10 + x^9 + x^6 + x^3 + x^2

In [159]:
h1 = gcd(g, g2)
h1

x^18 + x^17 + x^13 + x^10 + x^8 + x^7 + x^6 + x + 1

In [160]:
gcd(h1, h1.diff())

1

In [161]:
h2 = gcd(g, g2 - 1)
h2

x^8 + x^7 + x^6 + x^3 + x^2 + x + 1

In [162]:
gcd(h2, h2.diff())

1

In [163]:
menor_indice_cuerpo(h1, 2, x)

77

$77 > grado(h1)$ así que puede romper

In [164]:
factor(h1)

(x^7 + x^3 + 1) * (x^11 + x^10 + x^7 + x^4 + x^3 + x + 1)

Sus factores son $(x^7 + x^3 + 1) * (x^{11} + x^{10} + x^7 + x^4 + x^3 + x + 1)$

In [165]:
gcd(
    x^18 + x^17 + x^13 + x^10 + x^8 + x^7 + x^6 + x + 1, 
    (x^18 + x^17 + x^13 + x^10 + x^8 + x^7 + x^6 + x + 1).diff()
)

1

In [166]:
h3 = x^7 + x^3 + 1
h4 = x^11 + x^10 + x^7 + x^4 + x^3 + x + 1

In [167]:
h2*h3*h4

x^26 + x^23 + x^20 + x^19 + x^18 + x^16 + x^15 + x^10 + x^8 + x^4 + 1

In [168]:
h2*h3*h4 == g

True

Hemos descrito los pasos manualmente. El siguiente algoritmo generalizará lo que acabamos de realizar:

In [171]:
def es_irreducible(f, field):
    return all( list( map(
        lambda polinomio, num: polinomio(num) != 0, 
        [f]*field.modulus(), 
        range(0, field.modulus())
    )))


def romper(g, p, field):
    x = field.gen()
    if gcd(g, g.diff()) != 1:
        print("PROBLEMA: " + str(g) + " no es libre de cuadrados")
    
    indice = menor_indice_cuerpo(g, p, x)
    
    irreducibles = []
    if indice <= g.degree() and es_irreducible(g, field):
        print(str(g) + " es irreducible")
        return [g] 
    else:
        print(str(g) + " es reducible")
        print("Se espera que se necesiten polinomios de grados " + str(factor(indice)))
        
        B = extraer_B(g, p, field)
        soluciones = sacar_soluciones(B, g, field)
        soluciones.remove(1)

        print("Entramos en fase de gcd(g, g - c)")
        for pol in soluciones:
            print("-> gcds de " + str(pol) + ":")
            
            for c in range(0, field.modulus()):
                roto = gcd(pol - c , g)
                print("\t" + str(roto))
                
                if roto == 1: 
                    continue
                
                irreducibles = list(
                    set(irreducibles + romper(roto, p, field))
                )
                
    return irreducibles

In [172]:
romper(g, 2, Z2)

x^26 + x^23 + x^20 + x^19 + x^18 + x^16 + x^15 + x^10 + x^8 + x^4 + 1 es reducible
Se espera que se necesiten polinomios de grados 2^3 * 7 * 11
Entramos en fase de gcd(g, g - c)
-> gcds de x^25 + x^23 + x^17 + x^16 + x^10 + x^9 + x^6 + x^3 + x^2:
	x^18 + x^17 + x^13 + x^10 + x^8 + x^7 + x^6 + x + 1
x^18 + x^17 + x^13 + x^10 + x^8 + x^7 + x^6 + x + 1 es reducible
Se espera que se necesiten polinomios de grados 7 * 11
Entramos en fase de gcd(g, g - c)
-> gcds de x^16 + x^14 + x^12 + x^11 + x^9 + x^7 + x^6 + x^4:
	x^11 + x^10 + x^7 + x^4 + x^3 + x + 1
x^11 + x^10 + x^7 + x^4 + x^3 + x + 1 es irreducible
	x^7 + x^3 + 1
x^7 + x^3 + 1 es irreducible
	x^8 + x^7 + x^6 + x^3 + x^2 + x + 1
x^8 + x^7 + x^6 + x^3 + x^2 + x + 1 es irreducible
-> gcds de x^22 + x^20 + x^17 + x^13 + x^11 + x^7 + x^6 + x^5 + x^4 + x^3:
	x^11 + x^10 + x^7 + x^4 + x^3 + x + 1
x^11 + x^10 + x^7 + x^4 + x^3 + x + 1 es irreducible
	x^15 + x^14 + x^13 + x^11 + x^5 + x^4 + x^2 + x + 1
x^15 + x^14 + x^13 + x^11 + x^5 + x^4 + 

[x^7 + x^3 + 1,
 x^11 + x^10 + x^7 + x^4 + x^3 + x + 1,
 x^8 + x^7 + x^6 + x^3 + x^2 + x + 1]

## Apartado 4

El proceso será el mismo que el del apartado anterior. Aunque podríamos utilizar directamente `romper()`, mostraremos todos los pasos con detalle, enseñando al final el resultado de dicha función.

In [123]:
Z3 = PolynomialRing(GF(3), 'x')
x = Z3.gen()
g = 1 + x^4 + x^8 + x^10 + x^15 + x^16 + x^18 + x^19 + x^20 + x^23 + x^26
g

x^26 + x^23 + x^20 + x^19 + x^18 + x^16 + x^15 + x^10 + x^8 + x^4 + 1

In [124]:
menor_indice_cuerpo(g, 3, x)

133

In [125]:
B = extraer_B(g, 3, Z3)
B

26 x 26 dense matrix over Univariate Polynomial Ring in x over Finite Field of size 3 (use the '.str()' method to see the entries)

In [126]:
print(B)

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 2 0 0 0 2 0 0 0 2 0 2 0 0 0 0 2 2 0 2 2 2 0 0 2 0]
[0 1 0 0 2 1 0 0 2 1 0 1 2 0 2 0 1 1 0 0 0 1 2 2 0 0]
[1 0 0 0 2 0 0 2 2 0 1 2 1 0 1 0 1 2 1 2 2 0 0 1 1 2]
[2 2 1 1 2 2 1 2 2 2 2 1 1 1 2 0 1 1 0 2 1 1 0 1 2 1]
[2 1 2 2 1 2 0 2 1 2 0 0 1 2 1 0 1 2 1 1 0 0 1 0 2 2]
[0 1 1 2 1 0 0 1 2 1 0 2 0 0 0 1 0 0 1 2 1 0 2 0 1 2]
[0 2 1 0 1 0 0 1 0 2 2 1 2 0 2 0 2 0 2 2 0 1 0 1 2 0]
[2 1 0 0 1 2 0 1 2 1 0 1 2 2 1 1 0 0 2 2 0 0 2 2 2 0]
[1 1 0 2 2 1 0 1 0 1 2 0 1 0 1 0 1 2 2 2 2 0 2 1 1 2]
[2 2 1 1 0 2 0 2 0 2 1 2 2 2

In [127]:
(B - Matrix.identity(g.degree()))

26 x 26 dense matrix over Univariate Polynomial Ring in x over Finite Field of size 3 (use the '.str()' method to see the entries)

In [128]:
(B - Matrix.identity(g.degree())).rank()

24

In [132]:
polinomios_soluciones = sacar_soluciones(B, g, Z3)
polinomios_soluciones

[1,
 x^25 + x^23 + x^22 + 2*x^20 + x^19 + x^18 + 2*x^16 + x^15 + 2*x^14 + 2*x^13 + x^12 + x^11 + x^10 + 2*x^8 + 2*x^6 + x^5 + 2*x^2]

In [133]:
for pol in polinomios_soluciones:
    if pol != 1:
        print(gcd(g, pol))
        print(gcd(g, pol - 1))
        print(gcd(g, pol - 2))

x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1
x^7 + x^5 + x^4 + x^3 + x^2 + 2*x + 1
1


In [137]:
g == (x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1)*(x^7 + x^5 + x^4 + x^3 + x^2 + 2*x + 1)


True

In [135]:
gcd(
    x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1, 
    (x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1).diff()
)

1

Finalmente, automatizando el proceso:

In [122]:
romper(g, 3, Z3)

x^26 + x^23 + x^20 + x^19 + x^18 + x^16 + x^15 + x^10 + x^8 + x^4 + 1 es reducible
Se espera que se necesiten polinomios de grados 7 * 19
Entramos en fase de gcd(g, g - c)
-> gcds de x^25 + x^23 + x^22 + 2*x^20 + x^19 + x^18 + 2*x^16 + x^15 + 2*x^14 + 2*x^13 + x^12 + x^11 + x^10 + 2*x^8 + 2*x^6 + x^5 + 2*x^2:
	x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1
x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1 es irreducible
	x^7 + x^5 + x^4 + x^3 + x^2 + 2*x + 1
x^7 + x^5 + x^4 + x^3 + x^2 + 2*x + 1 es irreducible
	1


[x^7 + x^5 + x^4 + x^3 + x^2 + 2*x + 1,
 x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1]

## Apartado 5

En el apartado 2, hemos visto que el polinomio se descompone en un producto de tres polinomios, de grados $7, 8$ y $11$. Sin embargo, en el apartado 3, descompone como dos polinomios de grados $7$ y $19$. Esto nos dice que las factorizaciones son incompatbiles, por lo que el polinomio es irreducible en $\mathbb{Z}[x]$

## Temporal

In [37]:
x = Z2.gen()

In [38]:
f_alba = 1 + x^2 + x^6 + x^7 + x^8 + x^11 + x^14 + x^15 + x^21 + x^23 + x^26
menor_indice_cuerpo(f_alba, 2, x)

153

In [39]:
esperanza = 1 + x + x^2 + x^3 + x^4 + x^6 + x^7 + x^8 + x^10 + x^11 + x^14
menor_indice_cuerpo(esperanza, 2, x)

33

In [40]:
print(extraer_B(f_alba, Z2))

TypeError: extraer_B() missing 1 required positional argument: 'field'

In [41]:
g_paula = x^25 + x^23 + x^22 + x^21 + x^20 + x^14 + x^13 + x^12 + x^11 + x^9 + x^8 + x^5 + x^3 + x^2 + x + 1

In [43]:
(extraer_B(g_paula, 2, Z2) - Matrix.identity(g_paula.degree())).rank()

21

In [45]:
extraer_B(g_paula, 2, Z2)

25 x 25 dense matrix over Univariate Polynomial Ring in x over Finite Field of size 2 (using GF2X) (use the '.str()' method to see the entries)

In [47]:
sols_paula = (extraer_B(g_paula, 2, Z2) - Matrix.identity(g_paula.degree())).left_kernel()

In [48]:
print(sols_paula)

Free module of degree 25 and rank 4 over Univariate Polynomial Ring in x over Finite Field of size 2 (using GF2X)
Echelon basis matrix:
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 1 1 0 1 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0]
[0 0 1 1 0 1 0 1 1 1 1 0 0 0 1 1 1 1 0 0 1 0 1 0 1]
[0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 1 1 0]


In [49]:
for sol in list(sols_paula.gens()):
    print(Z2(list(sol)))

1
x^22 + x^18 + x^17 + x^12 + x^9 + x^7 + x^5 + x^3 + x^2 + x
x^24 + x^22 + x^20 + x^17 + x^16 + x^15 + x^14 + x^10 + x^9 + x^8 + x^7 + x^5 + x^3 + x^2
x^23 + x^22 + x^21 + x^20 + x^19 + x^18 + x^12 + x^8 + x^6 + x^3


In [184]:
x = Z3.gen()
menor_indice_cuerpo(2 + x^2 + x^4, 3, x)

4

In [186]:
factor(2 + x^2 + x^4)

x^4 + x^2 + 2

In [188]:
fds = 2 + x^2 + 2*x^7 + 2*x^8 + 2*x^9 + 2*x^10 + x^12 + 2*x^13 + 2*x^14 + x^15 + 2*x^18 + x^19 + 2*x^20 + x^22

In [189]:
menor_indice_cuerpo(fds, 3, x)

56

In [239]:
menor_indice_cuerpo(x^15 + x^14 + x^13 + x^11 + x^7 + x^6 + x + 1, 2, Z2.gen())

14

In [254]:
romper(x^15 + x^14 + x^13 + x^11 + x^7 + x^6 + x + 1, 2, Z2)

x^15 + x^14 + x^13 + x^11 + x^7 + x^6 + x + 1 es reducible
Se espera que se necesiten polinomios de grados 2 * 7
Entramos en fase de gcd(g, g - c)
-> gcds de x^14 + x^12 + x^11 + x^6
	x + 1
x + 1 es irreducible
	x^14 + x^12 + x^11 + x^6 + 1
x^14 + x^12 + x^11 + x^6 + 1 es irreducible


[x^14 + x^12 + x^11 + x^6 + 1, x + 1]

In [243]:
factor(x^15 + x^14 + x^13 + x^11 + x^7 + x^6 + x + 1)

(x + 1) * (x^14 + x^12 + x^11 + x^6 + 1)

In [245]:
gcd(diff(x^15 + x^14 + x^13 + x^11 + x^7 + x^6 + x + 1), (x^15 + x^14 + x^13 + x^11 + x^7 + x^6 + x + 1))

1

In [246]:
gcd(x^7 + x^4 + x^2 + 1, (x^7 + x^4 + x^2 + 1).diff())

1

In [255]:
(1 + x^2 + x^6).diff()

0

In [80]:
menor_indice_cuerpo_v2(
    1 + x + x^2 + x^3 + x^4 + x^6 + x^7 + x^8 + x^10 + x^11 + x^14, 
    2, 
    Z2.gen()
)

33

In [91]:
romper(1 + x + x^2 + x^3 + x^4 + x^6 + x^7 + x^8 + x^10 + x^11 + x^14, 2, Z2)

x^14 + x^11 + x^10 + x^8 + x^7 + x^6 + x^4 + x^3 + x^2 + x + 1 es reducible
Se espera que se necesiten polinomios de grados 3 * 11
Entramos en fase de gcd(g, g - c)
-> gcds de x^12 + x^11 + x^10 + x^9 + x^7 + x^5 + x^4 + x^2 + x:
	x^3 + x + 1
x^3 + x + 1 es irreducible
	x^11 + x^9 + x^6 + x^5 + x^3 + x^2 + 1
x^11 + x^9 + x^6 + x^5 + x^3 + x^2 + 1 es irreducible


[x^3 + x + 1, x^11 + x^9 + x^6 + x^5 + x^3 + x^2 + 1]

In [93]:
g_profesor_2 = 1 + x + x^5 + x^6 + x^8 + x^10 + x^11 + x^17 + x^20
g_profesor_2

x^20 + x^17 + x^11 + x^10 + x^8 + x^6 + x^5 + x + 1

In [ ]:
menor_indice_cuerpo

In [85]:
g_ana = 1 + x^5 + x^6 + x^8 + x^10 + x^11 + x^13 + x^15 + x^17 + x^21 + x^23 + x^26

In [94]:
gcd(g_ana, g_ana.diff())

1

In [86]:
menor_indice_cuerpo(g_ana, 2, x)

46

In [87]:
factor(46)

2 * 23

In [89]:
romper(g_ana, 2, Z2)

x^26 + x^23 + x^21 + x^17 + x^15 + x^13 + x^11 + x^10 + x^8 + x^6 + x^5 + 1 es reducible
Se espera que se necesiten polinomios de grados 2 * 23
Entramos en fase de gcd(g, g - c)
-> gcds de x^24 + x^23 + x^19 + x^18 + x^16 + x^14 + x^12 + x^10 + x^6 + x^5 + x^4 + x^3 + x:
	x^2 + x + 1
x^2 + x + 1 es irreducible
	x^24 + x^23 + x^19 + x^18 + x^16 + x^14 + x^12 + x^10 + x^6 + x^5 + x^4 + x^3 + x + 1
x^24 + x^23 + x^19 + x^18 + x^16 + x^14 + x^12 + x^10 + x^6 + x^5 + x^4 + x^3 + x + 1 es reducible
Se espera que se necesiten polinomios de grados 23
Entramos en fase de gcd(g, g - c)
-> gcds de x^23 + x^18 + x^15 + x^14 + x^11 + x^10 + x^5 + x^3:
	x + 1
x + 1 es reducible
Se espera que se necesiten polinomios de grados 1
Entramos en fase de gcd(g, g - c)
	x^23 + x^18 + x^15 + x^14 + x^11 + x^10 + x^5 + x^3 + 1
x^23 + x^18 + x^15 + x^14 + x^11 + x^10 + x^5 + x^3 + 1 es irreducible
-> gcds de x^25 + x^20 + x^17 + x^16 + x^13 + x^12 + x^7 + x^5 + x^2:
	x^23 + x^18 + x^15 + x^14 + x^11 + x^10 + x^

[x^23 + x^18 + x^15 + x^14 + x^11 + x^10 + x^5 + x^3 + 1, x^2 + x + 1]

In [173]:
g_ana.factor()

(x + 1) * (x^2 + x + 1) * (x^23 + x^18 + x^15 + x^14 + x^11 + x^10 + x^5 + x^3 + 1)

In [174]:
g.factor()

(x^7 + x^3 + 1) * (x^8 + x^7 + x^6 + x^3 + x^2 + x + 1) * (x^11 + x^10 + x^7 + x^4 + x^3 + x + 1)

In [175]:
y = Z3.gen()

In [176]:
menor_indice_cuerpo(
    2 + y^2 + y^4,
    3, 
    Z3.gen()
)

4

In [178]:
menor_indice_cuerpo(
    2 + 2*y + y^3 + 2*y^4 + y^5 + y^6 + 2*y^7 + 2*y^8 + y^9 + y^10 + y^11 + y^12, 
    3, 
    Z3.gen()
)

8

In [179]:
(2 + 2*y + y^3 + 2*y^4 + y^5 + y^6 + 2*y^7 + 2*y^8 + y^9 + y^10 + y^11 + y^12).factor()

(x^4 + x^2 + 2) * (x^8 + x^7 + x^2 + x + 1)