# Ejercicio 9 

Toma $n$ como tu número publicado para el ejercicio 2. Escribe $n$ en base 2, y usa esas cifras para definir un polinomio, $f(x)$, donde tu bit más significativo defina el grado del polinomio $n$, el siguiente bit va multiplicado por $x^{n-1}$ y así sucesivamente hasta que el bit menos significativo sea el término independiente. El polinomio que obtienes es universal en el sentido de que tiene coeficientes en cualquier anillo.

Sea $f(x)$ el polinomio que obtienes con coeficientes en $\mathbb{Z}$.

1. Toma $g(x) \equiv f(x) \pmod{2}$ y halla el menor cuerpo de característica 2 que contenga a todas las raíces de g. ¿Qué deduces sobre la irreducibilidad de $g(x)$ en $\mathbb{Z}_2[x]$?
2. Extrae la parte libre de cuadrados de $g(x)$ y calcúlale la matriz de Berlekamp por columnas. Resuelve el sistema lineal $(B - Id)X = 0$.
3. Aplica el algoritmo de Berlekamp recursivamente si es necesario para hallar la descomposición en irreducibles de $g(x)$ en $\mathbb{Z}_2[x]$.
4. Haz lo mismo para hallar la descomposición en irreducibles de $f(x) \pmod{3}$.
5. ¿Qué deduces sobre la reducibilidad de $f(x)$ en $\mathbb{Z}[x]$?

In [1]:
import numpy as np

In [2]:
n = 77432081

In [3]:
format(n, 'b')

'100100111011000010100010001'

In [4]:
Z2 = PolynomialRing(GF(2), 'x')
x = Z2.gen()
g = 1 + x^4 + x^8 + x^10 + x^15 + x^16 + x^18 + x^19 + x^20 + x^23 + x^26

## Apartado 1

In [5]:
def menor_indice_cuerpo(f, p, x):
    q = x^p
    q1 = (q - x).mod(f)
    k = 1
    #print("q1 = " + str(q1))
    
    while q1 != 0:
        q = (q^p).mod(f)
        q1 = (q - x).mod(f)
        k = k + 1
        
        #print("q = " + str(q))
        #print("q1 = " + str(q1))
    return k

In [6]:
menor_indice_cuerpo(g, 2, x)

616

El menor cuerpo de característica $2$ que contiene a todas las raíces de $g$ es $$F_{2^{2^3 * 7 * 11}} = F_{2^{8 * 7 * 11}}$$

In [7]:
factor(616)

2^3 * 7 * 11

Como $616 > \text{grado}(g) = 26$, entonces $g(x)$ es reducible en $\mathbb{Z}_2[x]$. (Esto no sale esto exactamente. Se rompe de otra manera. Mira el apartado 3) Por ello, $g(x)$ puede romperse en tres polinomios de grados $8, 7$ y $11$, ya que $8 + 7 + 11 = 26$

## Apartado 2

$g(x)$ es libre de cuadrados, así que no será necesario extraer nada. 

In [8]:
def extraer_B(g, p, field):
    # Asegúrate de que `g` está en el mismo cuerpo que `field`
    x = field.gen()
    B = np.zeros([g.degree(), g.degree()], dtype = int)

    for i in range(0, g.degree()):
        coeficientes = [0] * g.degree()

        pol = x^(p*i)
        pol = pol.mod(g)
        #print("[" + str(i) + "] x^2i mod f = " + str(pol))

        for j, coef in enumerate(pol.coefficients(sparse = False)):
            coeficientes[j] = coef

        B[i, :] = coeficientes
    return Matrix(field, B.tolist())

B = extraer_B(g, 2, Z2)

Nuestra matriz $B$ es 

In [9]:
B

26 x 26 dense matrix over Univariate Polynomial Ring in x over Finite Field of size 2 (using GF2X) (use the '.str()' method to see the entries)

In [10]:
print(B)

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 0 1 1 1 0 0 1 0 0]
[0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 0 1 1 1 0 0 1]
[0 1 0 0 1 1 0 0 1 1 0 1 1 0 1 0 1 1 0 0 0 1 1 1 0 0]
[0 0 0 1 0 0 1 1 0 0 1 1 0 1 1 0 1 0 1 1 0 0 0 1 1 1]
[1 1 0 0 1 0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 1 0 0 1 1 1]
[1 1 1 1 1 1 1 0 1 1 1 1 1 1

El rango de $B - I_d$ es $23$, así que habrá una única solución

In [11]:
(B - Matrix.identity(g.degree())).rank()

23

In [12]:
soluciones = (B - Matrix.identity(g.degree())).left_kernel()  # left o right?
soluciones

Free module of degree 26 and rank 3 over Univariate Polynomial Ring in x over Finite Field of size 2 (using GF2X)
Echelon basis matrix:
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 1 0 0 1 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1]
[0 0 0 1 1 1 1 1 0 0 0 1 0 1 0 0 0 1 0 0 1 0 1 0 0 0]

## Apartado 3

In [13]:
def sacar_soluciones(B, field):
    
    polinomios_soluciones = []
    soluciones = (B - Matrix.identity(g.degree())).left_kernel()

    for sol in list(soluciones.gens()):
        polinomios_soluciones.append(field(list(sol)))

    return polinomios_soluciones

polinomios_soluciones = sacar_soluciones(B, Z2)
polinomios_soluciones

[1,
 x^25 + x^23 + x^17 + x^16 + x^10 + x^9 + x^6 + x^3 + x^2,
 x^22 + x^20 + x^17 + x^13 + x^11 + x^7 + x^6 + x^5 + x^4 + x^3]

In [14]:
for pol in polinomios_soluciones:
    if pol != 1:
        print(gcd(g, pol))
        print(gcd(g, pol - 1))

x^18 + x^17 + x^13 + x^10 + x^8 + x^7 + x^6 + x + 1
x^8 + x^7 + x^6 + x^3 + x^2 + x + 1
x^11 + x^10 + x^7 + x^4 + x^3 + x + 1
x^15 + x^14 + x^13 + x^11 + x^5 + x^4 + x^2 + x + 1


In [15]:
gcd(
    x^18 + x^17 + x^13 + x^10 + x^8 + x^7 + x^6 + x + 1, 
    (x^18 + x^17 + x^13 + x^10 + x^8 + x^7 + x^6 + x + 1).diff()
)

1

In [16]:
gcd(
    x^8 + x^7 + x^6 + x^3 + x^2 + x + 1, 
    (x^8 + x^7 + x^6 + x^3 + x^2 + x + 1).diff()
)

1

In [17]:
(x^18 + x^17 + x^13 + x^10 + x^8 + x^7 + x^6 + x + 1) * (x^8 + x^7 + x^6 + x^3 + x^2 + x + 1), g


(x^26 + x^23 + x^20 + x^19 + x^18 + x^16 + x^15 + x^10 + x^8 + x^4 + 1,
 x^26 + x^23 + x^20 + x^19 + x^18 + x^16 + x^15 + x^10 + x^8 + x^4 + 1)

In [18]:
gcd(
    x^11 + x^10 + x^7 + x^4 + x^3 + x + 1,
    (x^11 + x^10 + x^7 + x^4 + x^3 + x + 1).diff()
)

1

In [19]:
gcd(
    x^15 + x^14 + x^13 + x^11 + x^5 + x^4 + x^2 + x + 1, 
    (x^15 + x^14 + x^13 + x^11 + x^5 + x^4 + x^2 + x + 1).diff()
)

1

In [20]:
(x^11 + x^10 + x^7 + x^4 + x^3 + x + 1) * (x^15 + x^14 + x^13 + x^11 + x^5 + x^4 + x^2 + x + 1), g

(x^26 + x^23 + x^20 + x^19 + x^18 + x^16 + x^15 + x^10 + x^8 + x^4 + 1,
 x^26 + x^23 + x^20 + x^19 + x^18 + x^16 + x^15 + x^10 + x^8 + x^4 + 1)

In [38]:
for pol in polinomios_soluciones:
    if pol != 1:
        print("Factores de " + str(gcd(g, pol)) + ":")
        print(factor(gcd(g, pol)))
        print("Factores de " + str(gcd(g, pol - 1)) + ":")
        print(factor(gcd(g, pol - 1)))

Factores de x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1:
x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1
Factores de x^7 + x^5 + x^4 + x^3 + x^2 + 2*x + 1:
x^7 + x^5 + x^4 + x^3 + x^2 + 2*x + 1


x^8 + x^7 + x^6 + x^3 + x^2 + x + 1

## Apartado 4

In [23]:
Z3 = PolynomialRing(GF(3), 'x')
x = Z3.gen()
g = 1 + x^4 + x^8 + x^10 + x^15 + x^16 + x^18 + x^19 + x^20 + x^23 + x^26
g

x^26 + x^23 + x^20 + x^19 + x^18 + x^16 + x^15 + x^10 + x^8 + x^4 + 1

In [24]:
menor_indice_cuerpo(g, 3, x)

133

In [25]:
B = extraer_B(g, 3, Z3)
B

26 x 26 dense matrix over Univariate Polynomial Ring in x over Finite Field of size 3 (use the '.str()' method to see the entries)

In [26]:
print(B)

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 2 0 0 0 2 0 0 0 2 0 2 0 0 0 0 2 2 0 2 2 2 0 0 2 0]
[0 1 0 0 2 1 0 0 2 1 0 1 2 0 2 0 1 1 0 0 0 1 2 2 0 0]
[1 0 0 0 2 0 0 2 2 0 1 2 1 0 1 0 1 2 1 2 2 0 0 1 1 2]
[2 2 1 1 2 2 1 2 2 2 2 1 1 1 2 0 1 1 0 2 1 1 0 1 2 1]
[2 1 2 2 1 2 0 2 1 2 0 0 1 2 1 0 1 2 1 1 0 0 1 0 2 2]
[0 1 1 2 1 0 0 1 2 1 0 2 0 0 0 1 0 0 1 2 1 0 2 0 1 2]
[0 2 1 0 1 0 0 1 0 2 2 1 2 0 2 0 2 0 2 2 0 1 0 1 2 0]
[2 1 0 0 1 2 0 1 2 1 0 1 2 2 1 1 0 0 2 2 0 0 2 2 2 0]
[1 1 0 2 2 1 0 1 0 1 2 0 1 0 1 0 1 2 2 2 2 0 2 1 1 2]
[2 2 1 1 0 2 0 2 0 2 1 2 2 2

In [27]:
(B - Matrix.identity(g.degree()))

26 x 26 dense matrix over Univariate Polynomial Ring in x over Finite Field of size 3 (use the '.str()' method to see the entries)

In [28]:
(B - Matrix.identity(g.degree())).rank()

24

In [29]:
polinomios_soluciones = sacar_soluciones(B, Z3)
polinomios_soluciones

[1,
 x^25 + x^23 + x^22 + 2*x^20 + x^19 + x^18 + 2*x^16 + x^15 + 2*x^14 + 2*x^13 + x^12 + x^11 + x^10 + 2*x^8 + 2*x^6 + x^5 + 2*x^2]

In [30]:
for pol in polinomios_soluciones:
    if pol != 1:
        print(gcd(g, pol))
        print(gcd(g, pol - 1))
        print(gcd(g, pol - 2))

x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1
x^7 + x^5 + x^4 + x^3 + x^2 + 2*x + 1
1


In [31]:
(x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1)*(x^7 + x^5 + x^4 + x^3 + x^2 + 2*x + 1), g


(x^26 + x^23 + x^20 + x^19 + x^18 + x^16 + x^15 + x^10 + x^8 + x^4 + 1,
 x^26 + x^23 + x^20 + x^19 + x^18 + x^16 + x^15 + x^10 + x^8 + x^4 + 1)

In [32]:
gcd(
    x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1, 
    (x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1).diff()
)

1

## Apartado 5

## Temporal

In [33]:
x = Z2.gen()

In [34]:
f_alba = 1 + x^2 + x^6 + x^7 + x^8 + x^11 + x^14 + x^15 + x^21 + x^23 + x^26
menor_indice_cuerpo(f_alba, 2, x)

153

In [35]:
esperanza = 1 + x + x^2 + x^3 + x^4 + x^6 + x^7 + x^8 + x^10 + x^11 + x^14
menor_indice_cuerpo(esperanza, 2, x)

33

In [36]:
print(extraer_B(f_alba, Z2))

TypeError: extraer_B() missing 1 required positional argument: 'field'

In [ ]:
g_paula = x^25 + x^23 + x^22 + x^21 + x^20 + x^14 + x^13 + x^12 + x^11 + x^9 + x^8 + x^5 + x^3 + x^2 + x + 1

In [ ]:
(extraer_B(g_paula, Z2) - Matrix.identity(g_paula.degree())).rank()

In [ ]:
extraer_B(g_paula, Z2)

In [ ]:
sols_paula = (extraer_B(g_paula, Z2) - Matrix.identity(g_paula.degree())).left_kernel()

In [ ]:
print(sols_paula)

In [ ]:
for sol in list(sols_paula.gens()):
    print(Z2(list(sol)))