# Ejercicio 9 

Toma $n$ como tu número publicado para el ejercicio 2. Escribe $n$ en base 2, y usa esas cifras para definir un polinomio, $f(x)$, donde tu bit más significativo defina el grado del polinomio $n$, el siguiente bit va multiplicado por $x^{n-1}$ y así sucesivamente hasta que el bit menos significativo sea el término independiente. El polinomio que obtienes es universal en el sentido de que tiene coeficientes en cualquier anillo.

Sea $f(x)$ el polinomio que obtienes con coeficientes en $\mathbb{Z}$.

1. Toma $g(x) \equiv f(x) \pmod{2}$ y halla el menor cuerpo de característica 2 que contenga a todas las raíces de g. ¿Qué deduces sobre la irreducibilidad de $g(x)$ en $\mathbb{Z}_2[x]$?
2. Extrae la parte libre de cuadrados de $g(x)$ y calcúlale la matriz de Berlekamp por columnas. Resuelve el sistema lineal $(B - Id)X = 0$.
3. Aplica el algoritmo de Berlekamp recursivamente si es necesario para hallar la descomposición en irreducibles de $g(x)$ en $\mathbb{Z}_2[x]$.
4. Haz lo mismo para hallar la descomposición en irreducibles de $f(x) \pmod{3}$.
5. ¿Qué deduces sobre la reducibilidad de $f(x)$ en $\mathbb{Z}[x]$?

In [1]:
import numpy as np

In [2]:
n = 77432081

In [3]:
format(n, 'b')

'100100111011000010100010001'

In [4]:
Z2 = PolynomialRing(GF(2), 'x')
x = Z2.gen()
g = 1 + x^4 + x^8 + x^10 + x^15 + x^16 + x^18 + x^19 + x^20 + x^23 + x^26

## Apartado 1

Vamos a encontrar el menor cuerpo de característica 2 que contiene a todas las raíces de $g$.

In [5]:
def menor_indice_cuerpo(f, p, x):
    g  = x^p 
    g1 = (g - x).mod(f)
    k  = 1
    
    while g1 > 0:
        g  = (g^p).mod(f)
        g1 = (g - x).mod(f)
        k  = k + 1
        
    return k

In [6]:
menor_indice_cuerpo(g, 2, x)

616

El menor cuerpo de característica $2$ que contiene a todas las raíces de $g$ es $$F_{2^{2^3 * 7 * 11}} = F_{2^{8 * 7 * 11}}$$

In [7]:
factor(616)

2^3 * 7 * 11

Como $616 > \text{grado}(g) = 26$, entonces $g(x)$ es reducible en $\mathbb{Z}_2[x]$. Por ello, $g(x)$ puede romperse en tres polinomios de grados $8, 7$ y $11$, ya que $8 + 7 + 11 = 26$

## Apartado 2

In [8]:
gcd(g, g.diff())

1

$g(x)$ es libre de cuadrados, así que no será necesario hacer ninguna extracción. 

In [9]:
def extraer_B(g, p, field):
    # Asegúrate de que `g` está en el mismo cuerpo que `field`
    x = field.gen()
    B = np.zeros([g.degree(), g.degree()], dtype = int)

    for i in range(0, g.degree()):
        coeficientes = [0] * g.degree()

        pol = x^(p*i)
        pol = pol.mod(g)
        #print("[" + str(i) + "] x^2i mod f = " + str(pol))

        for j, coef in enumerate(pol.coefficients(sparse = False)):
            coeficientes[j] = coef

        B[i, :] = coeficientes
    return Matrix(field, B.tolist())

B = extraer_B(g, 2, Z2)

Nuestra matriz $B$ es 

In [10]:
B

26 x 26 dense matrix over Univariate Polynomial Ring in x over Finite Field of size 2 (using GF2X) (use the '.str()' method to see the entries)

In [11]:
print(B)

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 0 1 1 1 0 0 1 0 0]
[0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 0 1 1 1 0 0 1]
[0 1 0 0 1 1 0 0 1 1 0 1 1 0 1 0 1 1 0 0 0 1 1 1 0 0]
[0 0 0 1 0 0 1 1 0 0 1 1 0 1 1 0 1 0 1 1 0 0 0 1 1 1]
[1 1 0 0 1 0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 1 0 0 1 1 1]
[1 1 1 1 1 1 1 0 1 1 1 1 1 1

In [12]:
(B - Matrix.identity(g.degree())).rank()

23

El rango de $B - I_d$ es $23$, así que habrá tres soluciones.

In [13]:
soluciones = (B - Matrix.identity(g.degree())).left_kernel()
soluciones

Free module of degree 26 and rank 3 over Univariate Polynomial Ring in x over Finite Field of size 2 (using GF2X)
Echelon basis matrix:
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 1 0 0 1 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1]
[0 0 0 1 1 1 1 1 0 0 0 1 0 1 0 0 0 1 0 0 1 0 1 0 0 0]

## Apartado 3

Encontremos la descomposición de $g(x)$ en irreducibles en $\mathbb{Z}_2[x]$. Primero, lo haremos a mano. Después introduciremos una función que realizará todo el proceso de estos tres primeros apartados, con lo cual conseguirá romper cualquier polinomio si se dan las condiciones adecuadas. 

In [14]:
def sacar_soluciones(B, g, field):
    
    polinomios_soluciones = []
    soluciones = (B - Matrix.identity(g.degree())).left_kernel()

    for sol in list(soluciones.gens()):
        polinomios_soluciones.append(field(list(sol)))

    return polinomios_soluciones

polinomios_soluciones = sacar_soluciones(B, g, Z2)
polinomios_soluciones

[1,
 x^25 + x^23 + x^17 + x^16 + x^10 + x^9 + x^6 + x^3 + x^2,
 x^22 + x^20 + x^17 + x^13 + x^11 + x^7 + x^6 + x^5 + x^4 + x^3]

Como $\text{grado}(g) - \text{rango}(B - I_d) = 3$, vamos a necesitar tres polinomios para romper $g$. Esto ya lo descubrimos en el primer apartado.

In [15]:
g.degree() - (B - Matrix.identity(g.degree())).rank()

3

Vamos a aplicar calcular el $\text{mcd}(g, \text{polinomio} - c)$, con $c \in \mathbb{Z}_2$

In [16]:
for pol in polinomios_soluciones:
    if pol != 1:
        print("gcds de " + str(pol) + ": ")
        for c in range(0, Z2.modulus()):
            print("\t-> " + str(gcd(pol - c , g)))

gcds de x^25 + x^23 + x^17 + x^16 + x^10 + x^9 + x^6 + x^3 + x^2: 
	-> x^18 + x^17 + x^13 + x^10 + x^8 + x^7 + x^6 + x + 1
	-> x^8 + x^7 + x^6 + x^3 + x^2 + x + 1
gcds de x^22 + x^20 + x^17 + x^13 + x^11 + x^7 + x^6 + x^5 + x^4 + x^3: 
	-> x^11 + x^10 + x^7 + x^4 + x^3 + x + 1
	-> x^15 + x^14 + x^13 + x^11 + x^5 + x^4 + x^2 + x + 1


In [17]:
g2 =  x^25 + x^23 + x^17 + x^16 + x^10 + x^9 + x^6 + x^3 + x^2

In [18]:
h1 = gcd(g, g2)
h1

x^18 + x^17 + x^13 + x^10 + x^8 + x^7 + x^6 + x + 1

In [19]:
gcd(h1, h1.diff())

1

In [20]:
h2 = gcd(g, g2 - 1)
h2

x^8 + x^7 + x^6 + x^3 + x^2 + x + 1

In [21]:
gcd(h2, h2.diff())

1

In [22]:
menor_indice_cuerpo(h1, 2, x)

77

$77 > grado(h1)$ así que puede romper

Sus factores son $(x^7 + x^3 + 1) (x^{11} + x^{10} + x^7 + x^4 + x^3 + x + 1)$:

In [23]:
(x^7 + x^3 + 1) * (x^11 + x^10 + x^7 + x^4 + x^3 + x + 1) == h1

True

In [24]:
gcd(
    x^18 + x^17 + x^13 + x^10 + x^8 + x^7 + x^6 + x + 1, 
    (x^18 + x^17 + x^13 + x^10 + x^8 + x^7 + x^6 + x + 1).diff()
)

1

In [25]:
h3 = x^7 + x^3 + 1
h4 = x^11 + x^10 + x^7 + x^4 + x^3 + x + 1

In [26]:
h2*h3*h4

x^26 + x^23 + x^20 + x^19 + x^18 + x^16 + x^15 + x^10 + x^8 + x^4 + 1

In [27]:
h2*h3*h4 == g

True

Hemos descrito los pasos manualmente. El siguiente algoritmo generalizará lo que acabamos de realizar:

In [28]:
def es_irreducible(f, field):
    return all( list( map(
        lambda polinomio, num: polinomio(num) != 0, 
        [f]*field.modulus(), 
        range(0, field.modulus())
    )))


def romper(g, p, field):
    x = field.gen()
    if gcd(g, g.diff()) != 1:
        print("PROBLEMA: " + str(g) + " no es libre de cuadrados")
    
    indice = menor_indice_cuerpo(g, p, x)
    
    irreducibles = []
    if indice <= g.degree() and es_irreducible(g, field):
        print(str(g) + " es irreducible")
        return [g] 
    else:
        print(str(g) + " es reducible")
        print("Se espera que se necesiten polinomios de grados " + str(factor(indice)))
        
        B = extraer_B(g, p, field)
        soluciones = sacar_soluciones(B, g, field)
        soluciones.remove(1)

        print("Entramos en fase de gcd(g, g - c)")
        for pol in soluciones:
            print("-> gcds de " + str(pol) + ":")
            
            for c in range(0, field.modulus()):
                roto = gcd(pol - c , g)
                print("\t" + str(roto))
                
                if roto == 1: 
                    continue
                
                irreducibles = list(
                    set(irreducibles + romper(roto, p, field))
                )
                
    return irreducibles

In [29]:
romper(g, 2, Z2)

x^26 + x^23 + x^20 + x^19 + x^18 + x^16 + x^15 + x^10 + x^8 + x^4 + 1 es reducible
Se espera que se necesiten polinomios de grados 2^3 * 7 * 11
Entramos en fase de gcd(g, g - c)
-> gcds de x^25 + x^23 + x^17 + x^16 + x^10 + x^9 + x^6 + x^3 + x^2:
	x^18 + x^17 + x^13 + x^10 + x^8 + x^7 + x^6 + x + 1
x^18 + x^17 + x^13 + x^10 + x^8 + x^7 + x^6 + x + 1 es reducible
Se espera que se necesiten polinomios de grados 7 * 11
Entramos en fase de gcd(g, g - c)
-> gcds de x^16 + x^14 + x^12 + x^11 + x^9 + x^7 + x^6 + x^4:
	x^11 + x^10 + x^7 + x^4 + x^3 + x + 1
x^11 + x^10 + x^7 + x^4 + x^3 + x + 1 es irreducible
	x^7 + x^3 + 1
x^7 + x^3 + 1 es irreducible
	x^8 + x^7 + x^6 + x^3 + x^2 + x + 1
x^8 + x^7 + x^6 + x^3 + x^2 + x + 1 es irreducible
-> gcds de x^22 + x^20 + x^17 + x^13 + x^11 + x^7 + x^6 + x^5 + x^4 + x^3:
	x^11 + x^10 + x^7 + x^4 + x^3 + x + 1
x^11 + x^10 + x^7 + x^4 + x^3 + x + 1 es irreducible
	x^15 + x^14 + x^13 + x^11 + x^5 + x^4 + x^2 + x + 1
x^15 + x^14 + x^13 + x^11 + x^5 + x^4 + 

[x^8 + x^7 + x^6 + x^3 + x^2 + x + 1,
 x^7 + x^3 + 1,
 x^11 + x^10 + x^7 + x^4 + x^3 + x + 1]

## Apartado 4

El proceso será el mismo que el del apartado anterior. Aunque podríamos utilizar directamente `romper()`, mostraremos todos los pasos con detalle, enseñando al final el resultado de dicha función.

In [30]:
Z3 = PolynomialRing(GF(3), 'x')
x = Z3.gen()
g = 1 + x^4 + x^8 + x^10 + x^15 + x^16 + x^18 + x^19 + x^20 + x^23 + x^26
g

x^26 + x^23 + x^20 + x^19 + x^18 + x^16 + x^15 + x^10 + x^8 + x^4 + 1

In [31]:
gcd(g, g.diff())

1

In [32]:
menor_indice_cuerpo(g, 3, x)

133

$133 > \text{grado}(g) \Rightarrow$ es reducible

In [33]:
B = extraer_B(g, 3, Z3)
B

26 x 26 dense matrix over Univariate Polynomial Ring in x over Finite Field of size 3 (use the '.str()' method to see the entries)

In [34]:
print(B)

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 2 0 0 0 2 0 0 0 2 0 2 0 0 0 0 2 2 0 2 2 2 0 0 2 0]
[0 1 0 0 2 1 0 0 2 1 0 1 2 0 2 0 1 1 0 0 0 1 2 2 0 0]
[1 0 0 0 2 0 0 2 2 0 1 2 1 0 1 0 1 2 1 2 2 0 0 1 1 2]
[2 2 1 1 2 2 1 2 2 2 2 1 1 1 2 0 1 1 0 2 1 1 0 1 2 1]
[2 1 2 2 1 2 0 2 1 2 0 0 1 2 1 0 1 2 1 1 0 0 1 0 2 2]
[0 1 1 2 1 0 0 1 2 1 0 2 0 0 0 1 0 0 1 2 1 0 2 0 1 2]
[0 2 1 0 1 0 0 1 0 2 2 1 2 0 2 0 2 0 2 2 0 1 0 1 2 0]
[2 1 0 0 1 2 0 1 2 1 0 1 2 2 1 1 0 0 2 2 0 0 2 2 2 0]
[1 1 0 2 2 1 0 1 0 1 2 0 1 0 1 0 1 2 2 2 2 0 2 1 1 2]
[2 2 1 1 0 2 0 2 0 2 1 2 2 2

In [35]:
(B - Matrix.identity(g.degree()))

26 x 26 dense matrix over Univariate Polynomial Ring in x over Finite Field of size 3 (use the '.str()' method to see the entries)

In [36]:
(B - Matrix.identity(g.degree())).rank()

24

Por tanto, hay dos soluciones.

In [37]:
polinomios_soluciones = sacar_soluciones(B, g, Z3)
polinomios_soluciones

[1,
 x^25 + x^23 + x^22 + 2*x^20 + x^19 + x^18 + 2*x^16 + x^15 + 2*x^14 + 2*x^13 + x^12 + x^11 + x^10 + 2*x^8 + 2*x^6 + x^5 + 2*x^2]

In [38]:
for pol in polinomios_soluciones:
    if pol != 1:
        print(gcd(g, pol))
        print(gcd(g, pol - 1))
        print(gcd(g, pol - 2))

x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1
x^7 + x^5 + x^4 + x^3 + x^2 + 2*x + 1
1


In [39]:
g == (x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1) * (x^7 + x^5 + x^4 + x^3 + x^2 + 2*x + 1)


True

In [40]:
gcd(
    x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1, 
    (x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1).diff()
)

1

Podemos obtener el mismo resultado con la función `romper()`:

In [41]:
romper(g, 3, Z3)

x^26 + x^23 + x^20 + x^19 + x^18 + x^16 + x^15 + x^10 + x^8 + x^4 + 1 es reducible
Se espera que se necesiten polinomios de grados 7 * 19
Entramos en fase de gcd(g, g - c)
-> gcds de x^25 + x^23 + x^22 + 2*x^20 + x^19 + x^18 + 2*x^16 + x^15 + 2*x^14 + 2*x^13 + x^12 + x^11 + x^10 + 2*x^8 + 2*x^6 + x^5 + 2*x^2:
	x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1
x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1 es irreducible
	x^7 + x^5 + x^4 + x^3 + x^2 + 2*x + 1
x^7 + x^5 + x^4 + x^3 + x^2 + 2*x + 1 es irreducible
	1


[x^7 + x^5 + x^4 + x^3 + x^2 + 2*x + 1,
 x^19 + 2*x^17 + x^12 + 2*x^7 + x^6 + x^3 + x + 1]

## Apartado 5

En el apartado 2, hemos visto que el polinomio se descompone en un producto de tres polinomios, de grados $7, 8$ y $11$. Sin embargo, en el apartado 3, descompone como dos polinomios de grados $7$ y $19$. Esto nos dice que las factorizaciones son incompatbiles, por lo que el polinomio es irreducible en $\mathbb{Z}[x]$