# Ejercicio 9 

Toma $n$ como tu número publicado para el ejercicio 2. Escribe $n$ en base 2, y usa esas cifras para definir un polinomio, $f(x)$, donde tu bit más significativo defina el grado del polinomio $n$, el siguiente bit va multiplicado por $x^{n-1}$ y así sucesivamente hasta que el bit menos significativo sea el término independiente. El polinomio que obtienes es universal en el sentido de que tiene coeficientes en cualquier anillo.

Sea $f(x)$ el polinomio que obtienes con coeficientes en $\mathbb{Z}$.

1. Toma $g(x) \equiv f(x) \pmod{2}$ y halla el menor cuerpo de característica 2 que contenga a todas las raíces de g. ¿Qué deduces sobre la irreducibilidad de $g(x)$ en $\mathbb{Z}_2[x]$?
2. Extrae la parte libre de cuadrados de $g(x)$ y calcúlale la matriz de Berlekamp por columnas. Resuelve el sistema lineal $(B - Id)X = 0$.
3. Aplica el algoritmo de Berlekamp recursivamente si es necesario para hallar la descomposición en irreducibles de $g(x)$ en $\mathbb{Z}_2[x]$.
4. Haz lo mismo para hallar la descomposición en irreducibles de $f(x) \pmod{3}$.
5. ¿Qué deduces sobre la reducibilidad de $f(x)$ en $\mathbb{Z}[x]$?

In [76]:
import numpy as np

In [37]:
n = 77432081

In [38]:
format(n, 'b')

'100100111011000010100010001'

In [39]:
Z2 = PolynomialRing(GF(2), 'x')
x = Z2.gen()
g = 1 + x^4 + x^8 + x^10 + x^15 + x^16 + x^18 + x^19 + x^20 + x^23 + x^26

## Apartado 1

In [31]:
def menor_indice_cuerpo(f, p):
    q = x^p
    q1 = (q - x).mod(f)
    k = 1
    #print("q1 = " + str(q1))
    
    while q1 != 0:
        q = (q^p).mod(f)
        q1 = (q - x).mod(f)
        k = k + 1
        
        #print("q = " + str(q))
        #print("q1 = " + str(q1))
    return k

In [36]:
menor_indice_cuerpo(g, 2)

616

El menor cuerpo de característica $2$ que contiene a todas las raíces de $g$ es $$F_{2^{2^3 * 7 * 11}} = F_{2^{8 * 7 * 11}}$$

In [40]:
factor(616)

2^3 * 7 * 11

Como $616 > \text{grado}(g) = 26$, entonces $g(x)$ es reducible en $\mathbb{Z}_2[x]$. Pore ello, $f(x)$ puede romperse en tres polinomios de grados $8, 7$ y $11$, ya que $8 + 7 + 11 = 26$

## Apartado 2

$g(x)$ es libre de cuadrados, así que no será necesario extraer nada. 

In [123]:
def extraer_B(g):
    B = np.zeros([g.degree(), g.degree()], dtype = int)

    for i in range(0, g.degree()):
        coeficientes = [0] * g.degree()

        pol = x^(2*i)
        pol = pol.mod(g)
        #print("[" + str(i) + "] x^2i mod f = " + str(pol))

        for j, coef in enumerate(pol.coefficients(sparse = False)):
            coeficientes[j] = coef

        B[i, :] = coeficientes
    return Matrix(B.tolist())

B = extraer_B(g)

Nuestra matriz $B$ es 

In [124]:
print(B)

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 0 1 1 1 0 0 1 0 0]
[0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 0 1 1 1 0 0 1]
[0 1 0 0 1 1 0 0 1 1 0 1 1 0 1 0 1 1 0 0 0 1 1 1 0 0]
[0 0 0 1 0 0 1 1 0 0 1 1 0 1 1 0 1 0 1 1 0 0 0 1 1 1]
[1 1 0 0 1 0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 1 0 0 1 1 1]
[1 1 1 1 1 1 1 0 1 1 1 1 1 1

El rango de $B - I_d$ es $25$, así que habrá una única solución

In [143]:
(B - Matrix.identity(g.degree())).rank()

25

In [144]:
print(
    (B - Matrix.identity(g.degree())).solve_right(zero_vector(g.degree()))
)

(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)


In [146]:
(B - Matrix.identity(g.degree())).right_kernel()

Free module of degree 26 and rank 1 over Integer Ring
Echelon basis matrix:
[  3  -2  -2 -85  -2 -10 -85 -28  -2  50 -10  71 -85 159 -28  83  -2  63  50  78 -10 -12  71 -29 -85  -8]

In [150]:
type((B - Matrix.identity(g.degree())).right_kernel())

<class 'sage.modules.free_module.FreeModule_submodule_pid_with_category'>

In [116]:
solve(B - np.identity(g.degree()), np.zeros(g.degree()))

TypeError: array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]) is not a valid variable.

25

## Apartado 3

## Apartado 4

## Apartado 5

## Temporal

In [32]:
f_alba = 1 + x^2 + x^6 + x^7 + x^8 + x^11 + x^14 + x^15 + x^21 + x^23 + x^26
menor_indice_cuerpo(f_alba, 2)

153

In [34]:
esperanza = 1 + x + x^2 + x^3 + x^4 + x^6 + x^7 + x^8 + x^10 + x^11 + x^14
menor_indice_cuerpo(esperanza, 2)

33

In [103]:
print(extraer_B(f_alba))

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [1 0 1 0 0 0 1 1 1 0 0 1 0 0 1 1 0 0 0 0 0 1 0 1 0 0]
 [0 0 1 0 1 0 0 0 1 1 1 0 0 1 0 0 1 1 0 0 0 0 0 1 0 1]
 [0 1 0 1 1 0 1 1 1 1 1 1 0 0 0 0 1 0 1 1 0 0 1 0 1 1]
 [1 1 1 0 0 1 0 0 1 0 1 0 0 1 1 0 1 0 1 0 1 0 1 1 0 0]
 [0 0 1 1 1 0 0 1 0 0 1 0 1 0 0 1 1 0 1 0 1 0 1 0 1 1]
 [1 1 1 1 

/opt/sage/local/lib/python2.7/site-packages/sage/repl/ipython_kernel/__main__.py:1: DeprecationWarning: The use of coeffs() is now deprecated in favor of coefficients(sparse=False).
See http://trac.sagemath.org/17518 for details.
  from ipykernel.kernelapp import IPKernelApp


In [94]:
g_paula = x^25 + x^23 + x^22 + x^21 + x^20 + x^14 + x^13 + x^12 + x^11 + x^9 + x^8 + x^5 + x^3 + x^2 + x + 1